### ISSUE TITLE
How did you use this library.

### ISSUE THREAD

**Issue by fkfouri** [jpdillingham/B2MML.NET#1]
Hello.

I´d like to know how did you use this library.

I am studying a way to generate a B2MML from Business Process Model.

Thanks in advanced!

**Comment by jpdillingham** [comment]
I created this library primarily to allow b2mml payloads to be serialized to/from XML, You can, however, use add a reference to the library and use it to build a model programmatically.

**Comment by fkfouri** [comment]
Hi
Do you know some BPMS that is possible to connect this library to create a XML based a process model. I know the Enterprise Architect as BPMS, but the database is based in MS-Access.

**Comment by jpdillingham** [comment]
Unfortunately this library is simply an implementation of the B2MML domain model; it doesn't contain any code.  The primary use cases would be usage as the target or source of a deserialization or serialization, respectively.

More specifically, if assuming you have an XML file containing B2MML, you'd use an XML library to deserialize your XML to an object of a type contained within this library before working with it programmatically.  This allows you to avoid manually parsing the file or deserializing to a generic XML document and traversing the nodes.
